"use strict";


// lvl1 draws icons from icons1 
let icons1 = [
    '<i class="fab fa-accessible-icon"></i>',
    '<i class="fab fa-accusoft"></i>',
    '<i class="fab fa-acquisitions-incorporated"></i>',
    '<i class="fas fa-ad"></i>',
    '<i class="fas fa-address-book"></i>',
    '<i class="fab fa-adn"></i>',
    '<i class="fab fa-adversal"></i>',
    '<i class="fas fa-adjust"></i>',
    '<i class="fab fa-accessible-icon"></i>',
    '<i class="fab fa-accusoft"></i>',
    '<i class="fab fa-acquisitions-incorporated"></i>',
    '<i class="fas fa-ad"></i>',
    '<i class="fas fa-address-book"></i>',
    '<i class="fab fa-adn"></i>',
    '<i class="fab fa-adversal"></i>',
    '<i class="fas fa-adjust"></i>'
];
// lvl2 and lvl4 draw icons from icons2
let icons2 = [
    [
        '<i class="fas fa-american-sign-language-interpreting"></i>',
        '<i class="fas fa-anchor"></i>',
        '<i class="fab fa-angular"></i>',
        '<i class="fab fa-apple-pay"></i>',
        '<i class="fas fa-air-freshener"></i>',
        '<i class="fab fa-algolia"></i>',
        '<i class="fab fa-alipay"></i>',
        '<i class="fab fa-affiliatetheme"></i>',
        '<i class="fab fa-accessible-icon"></i>',
        '<i class="fab fa-accusoft"></i>',
        '<i class="fab fa-acquisitions-incorporated"></i>',
        '<i class="fas fa-ad"></i>',
        '<i class="fas fa-address-book"></i>',
        '<i class="fab fa-adn"></i>',
        '<i class="fab fa-adversal"></i>',
        '<i class="fas fa-adjust"></i>'
    ],
    [
        '<i class="fas fa-american-sign-language-interpreting"></i>',
        '<i class="fas fa-anchor"></i>',
        '<i class="fab fa-angular"></i>',
        '<i class="fab fa-apple-pay"></i>',
        '<i class="fas fa-air-freshener"></i>',
        '<i class="fab fa-algolia"></i>',
        '<i class="fab fa-alipay"></i>',
        '<i class="fab fa-affiliatetheme"></i>',
        '<i class="fab fa-accessible-icon"></i>',
        '<i class="fab fa-accusoft"></i>',
        '<i class="fab fa-acquisitions-incorporated"></i>',
        '<i class="fas fa-ad"></i>',
        '<i class="fas fa-address-book"></i>',
        '<i class="fab fa-adn"></i>',
        '<i class="fab fa-adversal"></i>',
        '<i class="fas fa-adjust"></i>'
    ]
];
// lvl3 draws icons from icons3
let icons3 = [
    '<i class="fas fa-american-sign-language-interpreting"></i>',
    '<i class="fas fa-anchor"></i>',
    '<i class="fab fa-angular"></i>',
    '<i class="fab fa-apple-pay"></i>',
    '<i class="fas fa-air-freshener"></i>',
    '<i class="fab fa-algolia"></i>',
    '<i class="fab fa-alipay"></i>',
    '<i class="fab fa-affiliatetheme"></i>',
    '<i class="fab fa-accessible-icon"></i>',
    '<i class="fab fa-accusoft"></i>',
    '<i class="fab fa-acquisitions-incorporated"></i>',
    '<i class="fas fa-ad"></i>',
    '<i class="fas fa-address-book"></i>',
    '<i class="fab fa-adn"></i>',
    '<i class="fab fa-adversal"></i>',
    '<i class="fas fa-adjust"></i>',
    '<i class="fas fa-american-sign-language-interpreting"></i>',
    '<i class="fas fa-anchor"></i>',
    '<i class="fab fa-angular"></i>',
    '<i class="fab fa-apple-pay"></i>',
    '<i class="fas fa-air-freshener"></i>',
    '<i class="fab fa-algolia"></i>',
    '<i class="fab fa-alipay"></i>',
    '<i class="fab fa-affiliatetheme"></i>',
    '<i class="fab fa-accessible-icon"></i>',
    '<i class="fab fa-accusoft"></i>',
    '<i class="fab fa-acquisitions-incorporated"></i>',
    '<i class="fas fa-ad"></i>',
    '<i class="fas fa-address-book"></i>',
    '<i class="fab fa-adn"></i>',
    '<i class="fab fa-adversal"></i>',
    '<i class="fas fa-adjust"></i>',
    '<i class="fab fa-blackberry"></i>',
    '<i class="fab fa-black-tie"></i>',
    '<i class="fab fa-bity"></i>',
    '<i class="fas fa-birthday-cake"></i>',
    '<i class="fas fa-binoculars"></i>',
    '<i class="fas fa-bicycle"></i>',
    '<i class="fas fa-bezier-curve"></i>',
    '<i class="far fa-bell-slash"></i>',
    '<i class="fab fa-behance-square"></i>',
    '<i class="fas fa-bed"></i>',
    '<i class="fas fa-battery-half"></i>',
    '<i class="fas fa-bath"></i>',
    '<i class="fas fa-basketball-ball"></i>',
    '<i class="fab fa-bandcamp"></i>',
    '<i class="fas fa-band-aid"></i>',
    '<i class="fab fa-aws"></i>',
    '<i class="fab fa-blackberry"></i>',
    '<i class="fab fa-black-tie"></i>',
    '<i class="fab fa-bity"></i>',
    '<i class="fas fa-birthday-cake"></i>',
    '<i class="fas fa-binoculars"></i>',
    '<i class="fas fa-bicycle"></i>',
    '<i class="fas fa-bezier-curve"></i>',
    '<i class="far fa-bell-slash"></i>',
    '<i class="fab fa-behance-square"></i>',
    '<i class="fas fa-bed"></i>',
    '<i class="fas fa-battery-half"></i>',
    '<i class="fas fa-bath"></i>',
    '<i class="fas fa-basketball-ball"></i>',
    '<i class="fab fa-bandcamp"></i>',
    '<i class="fas fa-band-aid"></i>',
    '<i class="fab fa-aws"></i>'
];
// lvl4 draws icons from icons4
let icons4 = [
    [
        '<i class="fab fa-blackberry"></i>',
        '<i class="fab fa-black-tie"></i>',
        '<i class="fab fa-bity"></i>',
        '<i class="fas fa-birthday-cake"></i>',
        '<i class="fas fa-binoculars"></i>',
        '<i class="fas fa-bicycle"></i>',
        '<i class="fas fa-bezier-curve"></i>',
        '<i class="far fa-bell-slash"></i>',
        '<i class="fab fa-behance-square"></i>',
        '<i class="fas fa-bed"></i>',
        '<i class="fas fa-battery-half"></i>',
        '<i class="fas fa-bath"></i>',
        '<i class="fas fa-basketball-ball"></i>',
        '<i class="fab fa-bandcamp"></i>',
        '<i class="fas fa-band-aid"></i>',
        '<i class="fab fa-aws"></i>'
    ],
    [
        '<i class="fab fa-blackberry"></i>',
        '<i class="fab fa-black-tie"></i>',
        '<i class="fab fa-bity"></i>',
        '<i class="fas fa-birthday-cake"></i>',
        '<i class="fas fa-binoculars"></i>',
        '<i class="fas fa-bicycle"></i>',
        '<i class="fas fa-bezier-curve"></i>',
        '<i class="far fa-bell-slash"></i>',
        '<i class="fab fa-behance-square"></i>',
        '<i class="fas fa-bed"></i>',
        '<i class="fas fa-battery-half"></i>',
        '<i class="fas fa-bath"></i>',
        '<i class="fas fa-basketball-ball"></i>',
        '<i class="fab fa-bandcamp"></i>',
        '<i class="fas fa-band-aid"></i>',
        '<i class="fab fa-aws"></i>'
    ],
    [
        '<i class="fab fa-blackberry"></i>',
        '<i class="fab fa-black-tie"></i>',
        '<i class="fab fa-bity"></i>',
        '<i class="fas fa-birthday-cake"></i>',
        '<i class="fas fa-binoculars"></i>',
        '<i class="fas fa-bicycle"></i>',
        '<i class="fas fa-bezier-curve"></i>',
        '<i class="far fa-bell-slash"></i>',
        '<i class="fab fa-behance-square"></i>',
        '<i class="fas fa-bed"></i>',
        '<i class="fas fa-battery-half"></i>',
        '<i class="fas fa-bath"></i>',
        '<i class="fas fa-basketball-ball"></i>',
        '<i class="fab fa-bandcamp"></i>',
        '<i class="fas fa-band-aid"></i>',
        '<i class="fab fa-aws"></i>'
    ]
];